[project]
name = "src"
version = "0.1.0"

[tool.setuptools]
packages = ["src"]

[tool.mutmut]
paths_to_mutate = "src/energy/EnergyManagementSystem.py,src/flight/FlightBookingSystem.py,src/fraud/FraudDetectionSystem.py"